### ISSUE TITLE
Create a llvm-4 branch for PR

### ISSUE THREAD

**Issue by jcarlson23** [seahorn/llvm-seahorn#1]
@caballa Would you mind creating an llvm-4 branch (or something of the sort) that I could use for a PR soon (perhaps a day or two even)?  In the crab-llvm 4.0  port, I'm past the llvm-seahorn and into CRAB proper (disregarding DSA per your advice).  I don't see any tests in the this repo really (perhaps I'm missing something?) but I think a separate branch makes sense for a merge in the future?   I just want to run through my changes again, make a few notes, before creating a PR.

Thanks!

**Comment by caballa** [comment]
I've created branch llvm-4.0 in crab-llvm and llvm-seahorn repositories.

Yes, we don't have tests for llvm-seahorn ;-(

**Comment by jcarlson23** [comment]
Thank you!

**Comment by caballa** [comment]
Hi Jared,

FYI, I needed to port seahorn and llvm-seahorn to llvm 3.8
For llvm-seahorn I did what Arie suggested: diff relative to 3.6 and apply the differences to 3.8
Not sure if you were interesting in porting seahorn to 4.0 but if you are it might be easier to port from 3.8 rather than 3.6

**Comment by jcarlson23** [comment]
oh, nice, thanks.  Yeah, I did some of the 4.0 update after seeing what I overwrote but I'll use that as a means to double check.  Thanks!
